感谢您对我们的本地化内容做出贡献！ 
内容的所有贡献都需要遵守以下准则：
1. [Microsoft 语言风格指南](https://www.microsoft.com/Language/StyleGuides)描述了将英语翻译为其他语言时应如何理解文本。
2. [Microsoft 语言门户](https://www.microsoft.com/language)提供了 Microsoft 产品中使用的技术相关**术语**英文及其相应翻译。
加入我们不断发展的本地化社区时，访问 [社区本地化 Wiki](https://github.com/Microsoft/Localization/wiki)，可详细了解社区本地化计划及参与我们计划的其他方式。我们还会在此页上共享 PR 批准流程及一些 <PR 管理>提示。
不断投稿，可获得<本地化>贡献分，提升在 [参与者排行榜](https://microsoftl10n.github.io/)中的排名！

Microsoft 开发人员关系国际化组
